select
    resource_agency_num,
    parent_agency_num,
    public_name,
    alternate_name,
    -- official_name,
    taxonomy_level_name as table_name,
    eligibility,
    -- record_owner,
    -- unique_id_prior_system,
    physical_address_1,
    physical_address_2,
    physical_city,
    physical_county,
    physical_state_province,
    physical_postal_code,
    physical_country,
    physical_address_is_private,
    -- mailing_attention_name,
    mailing_address_1,
    mailing_address_2,
    mailing_city,
    mailing_state_province,
    mailing_postal_code,
    mailing_country,
    mailing_address_is_private,
    -- other_address_1,
    -- other_address_2,
    -- other_city,
    -- other_county,
    -- other_state_province,
    -- other_postal_code,
    -- other_country,
    latitude,
    longitude,
    hours_of_operation,
    phone_1_number,
    phone_1_name,
    phone_1_description,
    phone_1_is_private,
    -- phone_1_type,
    -- phone_2_number,
    -- phone_2_name,
    -- phone_2_description,
    -- phone_2_is_private,
    -- phone_2_type,
    -- phone_3_number,
    -- phone_3_name,
    -- phone_3_description,
    -- phone_3_is_private,
    -- phone_3_type,
    -- phone_4_number,
    -- phone_4_name,
    -- phone_4_description,
    -- phone_4_is_private,
    -- phone_4_type,
    -- phone_5_number,
    -- phone_5_name,
    -- phone_5_description,
    -- phone_5_is_private,
    -- phone_5_type,
    phone_fax,
    phone_fax_description,
    phone_fax_is_private,
    -- phone_tty,
    -- phone_tty_description,
    -- phone_tty_is_private,
    -- phone_toll_free,
    -- phone_toll_free_description,
    -- phone_toll_free_is_private,
    -- phone_number_hotline,
    -- phone_number_hotline_description,
    -- phone_number_hotline_is_private,
    -- phone_number_business_line,
    -- phone_number_business_line_description,
    -- phone_number_business_line_is_private,
    -- phone_number_out_of_area,
    -- phone_number_out_of_area_description,
    -- phone_number_out_of_area_is_private,
    -- phone_number_after_hours,
    -- phone_number_after_hours_description,
    -- phone_number_after_hours_is_private,
    email_address_main,
    website_address,
    agency_status,
    -- agency_classification,
    agency_description,
    -- search_hints,
    -- coverage_area,
    -- coverage_area_text,
    -- TODO: Reactivate this as soon as the data import is fixed. URGENT.
    -- eligibility,
    -- eligibility_adult,
    -- eligibility_child,
    -- eligibility_family,
    -- eligibility_female,
    -- eligibility_male,
    -- eligibility_teen,
    -- senior_worker_name,
    -- senior_worker_title,
    -- senior_worker_email_address,
    -- senior_worker_phone_number,
    -- senior_worker_is_private,
    -- main_contact_name,
    -- main_contact_title,
    -- main_contact_email_address,
    -- main_contact_phone_number,
    -- main_contact_type,
    -- main_contact_is_private,
    -- license_accreditation,
    -- i_r_s_status,
    -- f_e_i_n,
    -- year_incorporated,
    -- annual_budget_total,
    legal_status,
    -- source_of_funds,
    exclude_from_website,
    exclude_from_directory,
    -- TODO: Add accessibility once we have data.
    -- disabilities_access,
    -- physical_location_description,
    -- bus_service_access,
    -- public_access_transportation,
    -- payment_methods,
    fee_structure_source,
    application_process,
    -- resource_info,
    documents_required,
    languages_offered,
    -- TODO: Switch to structure list for filters once ready.
    -- languages_offered_list,
    -- availability_number_of_times,
    -- availability_frequency,
    -- availability_period,
    -- service_not_always_availability,
    -- capacity_type,
    -- service_capacity,
    -- normal_wait_time,
    temporary_message,
    -- temporary_message_appears,
    -- temporary_message_expires,
    entered_on as time_created,
    -- updated_on,
    -- made_inactive_on,
    -- internal_notes,
    -- internal_notes_for_editors_and_viewers,
    highlighted_resource,
    -- last_verified_on,
    -- last_verified_by_name,
    -- last_verified_by_title,
    -- last_verified_by_phone_number,
    -- last_verified_by_email_address,
    -- last_verification_approved_by,
    -- available_for_directory,
    -- available_for_referral,
    -- available_for_research,
    -- preferred_provider,
    connects_to_site_num,
    connects_to_program_num,
    -- language_of_record,
    -- current_workflow_step_code,
    -- volunteer_opportunities,
    -- volunteer_duties,
    -- is_link_only,
    -- program_agency_name_public,
    -- site_agency_name_public,
    -- categories,
    -- taxonomy_term,
    -- taxonomy_terms,
    -- taxonomy_terms_not_deactivated,
    -- taxonomy_codes,
    -- coverage,
    hours
from {{ source('database', 'table_name') }}
where agency_status = 'Active'
and (exclude_from_website = 'No' or exclude_from_website is null or exclude_from_website = '')
and (exclude_from_directory = 'No' or exclude_from_directory is null or exclude_from_directory = '')